env = LIBVA_DRIVER_NAME, nvidia
env = __GLX_VENDOR_LIBRARY_NAME, nvidia
exec-once = @greeter; hyprctl dispatch exit
windowrule = fullscreen, .*
windowrule = stayfocused, .*
monitor = , preferred, auto, 1
animations:enabled = false
misc {
  background_color = rgb(@base00)
  disable_autoreload = true
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  disable_splash_rendering = true
  disable_hyprland_qtutils_check = true
}
